### ISSUE TITLE
Size of the map of the dashboard

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#81]
The height of the map is not adapted of our usage as at the loading it centers on Africa. It does it as we have companies all-over the world.

The size of the map is currently 500px.

It should be updated to more than that. Most likely 1000px.

For that:
* [x] move the size of the map into a css class: #91
* [x] set media queries for the size of the map, (depends on #91) #92
* [x] Remove button over the map #103

**Comment by foutoucour** [comment]
The main div of the map is now driven by .geoengine_view css class.
The height remains set at 500px but should evolve after the work in #92
