### ISSUE TITLE
New Homepage

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#87]
The current homepage was done with the assumption the user knows what we are doing. Actually the homepage doesn't welcome or inform the user on anything we are doing.

We need to redefine the page. To prepare it:
* [ ]  set the text that inform about the new philosophy of the project (opensource, community based, etc.): #85
* [ ] Create a prototype of the page: #86

**Comment by foutoucour** [comment]
The new homepage should have:

* [ ] map of studios as it is on the current page.
* [ ] number of studios in cgstudiomap: #150 
* [ ] catch phrase
* [ ] link to sign in page
* [ ] a block text explaining our philosophy

**Comment by foutoucour** [comment]
last version of the homepage:
@M4rtine your point of view would be very welcome.
I want to close the ticket on Monday evening. 

![2015-07-08 21-50-51](https://cloud.githubusercontent.com/assets/547282/8640389/6ed05100-28c4-11e5-93bc-b9ccb8a04242.png)

**Comment by foutoucour** [comment]
@M4rtine updated the design in #175 

![homepage](https://cloud.githubusercontent.com/assets/547282/8699157/597a98b0-2ad1-11e5-813f-fde8a78b993e.png)
