### ISSUE TITLE
Report from user 1

### ISSUE THREAD

**Issue by foutoucour** [cgstudiomap/cgstudiomap#93]
The user is a alpha user, without interest in the industry. She has interest in directories as job hunter.

Here are the feedback she gave after a first try of the solution:
* [x] In company forms, some links are too long and they go over the border of the form. #94
* [x] The map in the section _Geo Localization_ is very handy! :+1: 
* [x] The little pop up to open the full form of the company, on the bottom left corner on the map, is great :+1: 
* [x] She didn't get what are the 3 little logos on the map #103 
* [x] Once she clicked on the _Measure a distance_ tool on the map, she didn't find how to get out of the tool #103 
* [x] The hand to navigate on the maps wasn't working for her. #103

**Comment by foutoucour** [comment]
Need to create issues for each points
* [x] link length (#94)
* [ ] logos on the map
* [ ] Measure distance tool
* [ ] hand tool
